# Generated by Django 3.0.7 on 2020-06-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20200625_2037'),
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='campaign.Campaign', verbose_name='campaign'),
            preserve_default=False,
        ),
    ]
