# Generated by Django 3.0.7 on 2020-07-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_campaign_abs_seconds'),
        ('tempdoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.PositiveIntegerField(db_index=True, verbose_name='sector')),
                ('layer', models.CharField(db_index=True, max_length=8, verbose_name='layer')),
                ('position', models.CharField(max_length=48, verbose_name='position')),
                ('value', models.CharField(max_length=96, verbose_name='value')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_elements', to='campaign.Campaign', verbose_name='campaign')),
            ],
        ),
        migrations.DeleteModel(
            name='TempDoc',
        ),
    ]
