# Generated by Django 3.0.7 on 2020-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempdoc', '0002_auto_20200721_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapelement',
            name='uuid',
            field=models.CharField(blank=True, db_index=True, max_length=48, null=True, verbose_name='uuid'),
        ),
        migrations.AlterField(
            model_name='mapelement',
            name='position',
            field=models.CharField(db_index=True, max_length=48, verbose_name='position'),
        ),
    ]
