# Generated by Django 3.0.7 on 2020-07-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempdoc', '0003_auto_20200724_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapelement',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
    ]
