//
// Reducer actions enumeration.  See store.js
//

export const actions = {
  "START_APP": "START_APP",
  "USER_KNOWN": "USER_KNOWN",
  "PLAYERS_KNOWN": "PLAYERS_KNOWN",
  "CREATE_PLAYER": "CREATE_PLAYER",
  "PLAYER_CREATED": "PLAYER_CREATED",
  "SELECT_PLAYER": "SELECT_PLAYER",
  "CAMPAIGNS_KNOWN": "CAMPAIGNS_KNOWN",
  "CREATE_CAMPAIGN": "CREATE_CAMPAIGN",
  "CAMPAIGN_CREATED": "CAMPAIGN_CREATED",
  "SELECT_CAMPAIGN": "SELECT_CAMPAIGN",
  "CLOSE_CAMPAIGN": "CLOSE_CAMPAIGN",
  "JOIN_CAMPAIGN": "JOIN_CAMPAIGN",
  "WANT_CHARACTERS": "WANT_CHARACTERS",
  "CHARACTERS_KNOWN": "CHARACTERS_KNOWN",
  "CREATE_CHARACTER": "CREATE_CHARACTER",
  "CHARACTER_CREATED": "CHARACTER_CREATED",
  "SHOW_ERROR": "SHOW_ERROR",
  "SHOW_ALERT": "SHOW_ALERT",
  "LOGIN": "LOGIN",
  "UPDATE_PLAYER": "UPDATE_PLAYER",
  "PLAYER_UPDATED": "PLAYER_UPDATED"
}

export default actions
