export const actions = {
  "START": "START",
  "USER_KNOWN": "USER_KNOWN",
  "PLAYERS_KNOWN": "PLAYERS_KNOWN",
  "CREATE_PLAYER": "CREATE_PLAYER",
  "PLAYER_CREATED": "PLAYER_CREATED",
  "FATAL_ERROR": "FATAL_ERROR"
}
