export const actions = {
  "START_APP": "START_APP",
  "USER_KNOWN": "USER_KNOWN",
  "PLAYERS_KNOWN": "PLAYERS_KNOWN",
  "CAMPAIGNS_KNOWN": "CAMPAIGNS_KNOWN",
  "CHARACTERS_KNOWN": "CHARACTERS_KNOWN",
  "CREATE_PLAYER": "CREATE_PLAYER",
  "PLAYER_CREATED": "PLAYER_CREATED",
  "CREATE_CAMPAIGN": "CREATE_CAMPAIGN",
  "CAMPAIGN_CREATED": "CAMPAIGN_CREATED",
  "SELECT_CAMPAIGN": "SELECT_CAMPAIGN",
  "CLOSE_CAMPAIGN": "CLOSE_CAMPAIGN",
  "CREATE_CHARACTER": "CREATE_CHARACTER",
  "CHARACTER_CREATED": "CHARACTER_CREATED",
  "FATAL_ERROR": "FATAL_ERROR"
}
