# Generated by Django 3.0.7 on 2020-07-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20200625_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='abs_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='absolute seconds'),
        ),
    ]
